// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VGwSVgbSUUnsgM0FnMOLar_Bi3mk5pk',
    appId: '1:860958272922:web:b4add9d1b2a6ba47411e23',
    messagingSenderId: '860958272922',
    projectId: 'elite-20496',
    authDomain: 'elite-20496.firebaseapp.com',
    storageBucket: 'elite-20496.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ3r5_mL-u2VuPpcjXM6uwrmulgAOfUiQ',
    appId: '1:860958272922:android:56ca4aad524a88f6411e23',
    messagingSenderId: '860958272922',
    projectId: 'elite-20496',
    storageBucket: 'elite-20496.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIEelSAPeIp7MSxI1DVGMdPvQqrD5UrV8',
    appId: '1:860958272922:ios:1447b8e1db8e0083411e23',
    messagingSenderId: '860958272922',
    projectId: 'elite-20496',
    storageBucket: 'elite-20496.firebasestorage.app',
    iosBundleId: 'com.example.elite',
  );
}
